#!/usr/bin/bash
# Lets you scroll through other images in the same folder of the image you
# opened.

folders=""

for image in "$@"; do
    dir=$(dirname "$image")
    folders="$folders $dir"
done

feh -Z --full-screen "$1" $folders
