#!/usr/bin/env bash

FILE=$(mktemp --suffix=".m3u")

for dir in "$@"; do
  find "$dir" \
    -print0 \
    -type f \
    -and \
    \( -not \
       \( -iname "*.cue" \
      -or -iname "*.log" \
      -or -iname "*.png" \
      -or -iname "*.jpg" \
      -or -iname "*.mp4" \
      -or -iname "*.mkv" \) \) \
    | xe -0 -N0 dirname \
    | sort \
    | uniq \
    >> "$FILE"
done

echo "$FILE"
