#!/bin/sh
# only laptop monitor active

# disable every monitor except eDP1
for output in $(xrandr --query | grep "\(dis\)*connected" | cut -d' ' -f 1); do
    if [ "$output" != eDP1 ]; then
        xrandr --output "$output" --off
    fi
done

xrandr --output eDP1 --auto
