#!/bin/sh
# home monitor setup

# sometimes these are not recognized
#xrandr --addmode DP2-1 1920x1080
#xrandr --addmode DP2-2 1920x1080

# xrandr --output eDP1 --off --output DP2-1 --off --output DP2-2 --off

#--output DP2-1  --mode 1920x1080 --rotate left --pos 0x0 \
xrandr --verbose \
    --output DP2-1  --mode 1920x1080 --primary     --pos 1150x620 \
    --output eDP1   --mode 1600x900                --pos 3200x1600
